- name: Install Zsh
  homebrew:
    name: zsh
    state: present
  tags: &tags_for_zsh_tasks [ 'install', 'productivity', 'dotfiles', 'zsh' ]

- name: Change the default shell to Zsh
  become: true
  command: "/usr/bin/sudo /usr/bin/chsh -s /bin/zsh"
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
  when: "'/bin/zsh' not in ansible_user_shell"
  tags: *tags_for_zsh_tasks
    
- name: Check if zsh is already installed
  stat:
    path: ~/.oh-my-zsh
  register: oh_my_stats
  tags: *tags_for_zsh_tasks

- name: Oh-My-Zsh
  shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh > ~/.oh-my-installer && chmod +x ~/.oh-my-installer && ~/.oh-my-installer
  when: oh_my_stats.stat.exists == False
  tags: *tags_for_zsh_tasks

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags: *tags_for_zsh_tasks

- name: Update .zshrc including zsh-autosuggestions
  shell: echo "source ~/.oh-my-zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh" >> ~/.zshrc
  tags: *tags_for_zsh_tasks
